In [2]:
## straight from the SciPy tutorial.

import numpy as np
from scipy.optimize import minimize

def rosen(x):
    """The Rosenbrock function"""
    return sum(100.0*(x[1:]-x[:-1]**2.0)**2.0 + (1-x[:-1])**2.0)

x0 = np.array([1.3, 0.7, 0.8, 1.9, 1.2])
res = minimize(rosen, x0, method='nelder-mead',
               options={'xatol': 1e-8, 'disp': True})

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 339
         Function evaluations: 571


In [3]:
# bounds
from scipy.optimize import Bounds
bounds = Bounds([0, -0.5], [1.0, 2.0])

# Linear constraints
from scipy.optimize import LinearConstraint
linear_constraint = LinearConstraint([[1, 2], [2, 1]], [-np.inf, 1], [1, 1])

# Nonlinear constraints
def cons_f(x):
    return [x[0]**2 + x[1], x[0]**2 - x[1]]
def cons_J(x):
    return [[2*x[0], 1], [2*x[0], -1]]
def cons_H(x, v):
    return v[0]*np.array([[2, 0], [0, 0]]) + v[1]*np.array([[2, 0], [0, 0]])
from scipy.optimize import NonlinearConstraint
nonlinear_constraint = NonlinearConstraint(cons_f, -np.inf, 1, jac=cons_J, hess=cons_H)

[1. 1. 1. 1. 1.]


# Hey look, this is a header.

## And a Second Level.

Text, huh? HOw about **bold**?

In [11]:
## Box optimization. limit the SA, maximize volume (from YouTube)

import numpy as np
from scipy.optimize import minimize

# Volume calculator. AKA our objective function.
def calcVolume(x):
    length=x[0]
    width=x[1]
    height=x[2]
    volume= length*width*height
    return volume

# Surface Area calc. Our constraint.
def calcSurface(x):
    length=x[0]
    width=x[1]
    height=x[2]
    surfaceArea=2*length*width + 2*height*length +2*height*width
    return surfaceArea

# objective function, based on Volume calculator.
def objective(x):
    return -calcVolume(x) # we'll maximize the volume by minimizing the neg.

def constraint(x): # The SA <= 10, or 10-SA >= 0, constraint. 
    return 10-calcSurface(x)

# yknow what, let's try another constraint.
def constraint2(x): # Let's say x[1] has to be 1.5 or more. So x[1]>=1.5
    
    return 10-calcSurface(x)

# Need a dictionary for the constraints.

cons = ({'type': 'ineq', 'fun':constraint}) # by convention this constraint is set >= 0.
# type is the KEY, and 'ineq' is the VALUE. For the VALUE of 'fun', we put 
# our function 'constraint'

# now let's guess.
lguess = 1
wguess = 1
hguess = 6

# we also need an ARRAY of the guesses.

x0= np.array([lguess, wguess, hguess])

# alright. time for our actual solver.
print('solving.')
sol= minimize(objective, x0, method='SLSQP', constraints=cons, options={'disp':True})
# OBJECTIVE is a function, x0 is your GUESS, CONSTRAINTS takes a dictionary.
# SLSQP can do constrained, non-linear.

# Our solutions!
print('solutions...')
xOpt=sol.x # pull the x VECTOR out of the solver.
volumeOpt=-sol.fun # what is this? It'll evaluate the obj function, but negate it.

surfaceAreaOpt=calcSurface(xOpt) # find our final SA.

print('length:' + str(xOpt[0]))
print('width:' + str(xOpt[1]))
print('height:' + str(xOpt[2]))
print('volume:' + str(volumeOpt))
print('SA:' + str(surfaceAreaOpt))












solving.
Optimization terminated successfully    (Exit mode 0)
            Current function value: -2.1516574122704815
            Iterations: 16
            Function evaluations: 73
            Gradient evaluations: 16
solutions...
length:1.290994534280064
width:1.2909945520063175
height:1.2909942585475396
volume:2.1516574122704815
SA:9.999999992907243


# Heading one

Hey look I wrote math.

$$
\begin{aligned}
&\text{minimize:} && (x_1-x_2)^2 + (x_2+x_3-2)^2 + (x_4-1)^2+(x_5-1)^2 \\\\
&\text{subject to:} && x_1 + 3x_2 = 0 \\\\
&&& x_3 + x_4 - 2x_5 = 0 \\\\
&&& x_2 - x_5 = 0 \\\\
&&& -10 \leq x_i \leq 10, \forall i=1,\ldots,5
\end{aligned}$$


## A Breakdown.

So, the constraints are 
1. Equality
2. Equality
3. Equality
4. Inequality bounding bewteen +/- 10

You could probably combine 1-3 in a linear constraint. AND 4 is basically a bounds constraint! (LaTeX formatting somehow works here??)
$$\begin{bmatrix} 0 \\ 0 \\ 0 \end{bmatrix}  \leq \begin{bmatrix} 1 & 3 & 0 & 0 & 0 \\ 0 & 0 & 1 & 1 & -2 \\ 0 & 1 & 0 & 0 & -5 \end{bmatrix}  \leq \begin{bmatrix} 0 \\ 0 \\ 0 \end{bmatrix}$$

In [31]:
# Let's try that again, with the specific HW problem.
import numpy as np
from scipy.optimize import minimize
from scipy.optimize import Bounds
from scipy.optimize import LinearConstraint

# Our objective function.
def objf(x):  # note x is a 5-dimentional vector.
    x1=x[0]
    x2=x[1]
    x3=x[2]
    x4=x[3]
    x5=x[4]

    return (x1-x2)**2  +(x2+x3-2)**2 + (x4-1)**2 + (x5-1)**2 # what a function!

# Test it!
# print(objf(np.array([1, 2, 3, 4, 5]))) # hey it works.

# Bounds object?

bounds = Bounds([-10, -10, -10, -10, -10],[10, 10, 10, 10, 10]) # all LOWER bounds and all UPPER bounds.

# linear constraint!
lin_con=LinearConstraint([[1,3,0,0,0],[0,0,1,1,-2],[0,1,0,0,-5]],[0,0,0],[0,0,0]) # by columns i guess?

# TAKE A GUESS.
x0_1=np.array([.5, .5, 1, 1, 1]) # this is a row.
print(x0) # looks OK.
print(x0[1])
print(objf(x0))


[0.5 0.5 1.  1.  1. ]
0.5
0.25


In [16]:
print(lin_con)

In [36]:
# Let's do it I guess?

sol= minimize(objf,x0, method='SLSQP',constraints=lin_con,options={'disp':True}, bounds=bounds)


# and finally,
print('The solution--------------')
opx=sol.x
print(opx)
print(sol.fun)
print(opx[0]+3*opx[1])

Optimization terminated successfully    (Exit mode 0)
            Current function value: 5.189189189593064
            Iterations: 7
            Function evaluations: 44
            Gradient evaluations: 7
The solution--------------
[-0.40539178  0.13513059  0.45945567 -0.40540343  0.02702612]
5.189189189593064
-5.551115123125783e-17


## SO.

All the framework is there. we just now need to run it with different ICs and then see if it changes.

In [37]:
x0_1=np.array([.5, 25, 1, 0, 1]) 
sol1= minimize(objf,x0, method='SLSQP',constraints=lin_con,options={'disp':True}, bounds=bounds)

print('The solution--------------')
opx_1=sol1.x
print(opx_1)
print(sol1.fun)
print(opx_1[0]+3*opx_1[1])

Optimization terminated successfully    (Exit mode 0)
            Current function value: 5.189189189593064
            Iterations: 7
            Function evaluations: 44
            Gradient evaluations: 7
The solution--------------
[-0.40539178  0.13513059  0.45945567 -0.40540343  0.02702612]
5.189189189593064
-5.551115123125783e-17


Hey look, it's the same solution. **yee. haw.**

**Anyway let's try out some more math type while we're here.**

$e^{i*\pi} +1 = 0$ is a beautiful equation

Oooo! I can put an equation in here. $ a^2 + b^2 = c^2 $  *wheeeee* Then if I want a line break: $$ x^2 = -3+5y $$

$$
\begin{array}{}
x_1 & x_2 & \ldots \\\\
x_3 & x_4 & \ldots \\\\
\vdots & \vdots & \ddots
\end{array}
$$

In [1]:
# Professor's way

from ___ import minimize here

fun = lambda x: (x)....function here

# a library of constraints
cons = ({'type'...})

bnds = ((-10,10)....and more)

res= minimize(fun,(1,2,3,4,1), method='SLSQP', bounds=bnds, constraints=cons)
# note that we put the arguments straight into the minimize function.


SyntaxError: invalid syntax (<ipython-input-1-d393f5c72433>, line 3)